name: Verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['24.1.7']
        elixir: ['1.13.0']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - name: Compile Dependencies
        run: mix deps.compile
      - name: Tests
        run: mix test
      - name: Format
        run: mix format --check-formatted
      - name: Credo
        run: mix credo --mute-exit-status

      - name: Retrieve cached PLT
        uses: actions/cache@v2
        id: plt-cache
        with:
          path: |
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - name: Create PLT
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt
      - name: Dialyzer
        run: MIX_ENV=dev mix dialyzer --no-check